import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import { AppHelpFab } from "../components/app-help-fab";
import "./globals.css";

/** UI sans — Inter matches garage web reference (geometric UI sans, Cyrillic). */
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${inter.variable} ${geistMono.variable} h-full antialiased`}
      style={{
        backgroundColor: "#080d12",
        colorScheme: "dark",
      }}
    >
      <body
        className="mototwin-dark min-h-full flex flex-col"
        style={{
          margin: 0,
          backgroundColor: "#080d12",
        }}
      >
        {children}
        <AppHelpFab />
      </body>
    </html>
  );
}
